### ISSUE TITLE
Failed test: BasePageTest.convertsToXml:67

### ISSUE THREAD

**Issue by simonjenga** [yegor256/rexsl#808]
```
Running com.rexsl.page.BasePageTest
[?[0;37mINFO?[m] com.jcabi.aspects.aj.NamedThreads: jcabi-aspects 0.17.2/5df901f started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.262 sec <<< FAILURE! - in com.rexsl.page.BasePageTest
convertsToXml(com.rexsl.page.BasePageTest)  Time elapsed: 2.271 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: (an XML document with XPath /page/@date and an XML document with XPath /page/@ip and an XML document with XPath /page/@ssl and an XML document with XPath /page[number(@sla) > 0] and an XML document with XPath /page/millis and an XML document with XPath /page/single/x and an XML document with XPath /page/title[. = 'hello, world!'] and an XML document with XPath /page/links/link[@rel = 'home'] and an XML document with XPath /page/links/link[@rel = 'self'] and an XML document with XPath /page/links/link[@rel = 'test'])
     but: an XML document with XPath /page[number(@sla) > 0] was <<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<page date="2014-09-10T23:41:28.841+03:00" ip="105.161.21.119" sla="-1.000" ssl="false">
    <single>
        <x/>
    </single>
    <title>hello, world!</title>
    <links>
        <link href="http://localhost:99/foo" rel="test" type="text/xml"/>
        <link href="http://localhost:99/local/foo" rel="self" type="text/xml"/>
        <link href="http://localhost:99/" rel="home" type="text/xml"/>
    </links>
    <millis>1376</millis>
</page>
>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.rexsl.page.BasePageTest.convertsToXml(BasePageTest.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

Running com.rexsl.core.UserAgentTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.19 sec - in com.rexsl.core.UserAgentTest
Running com.rexsl.page.auth.GithubTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.227 sec - in com.rexsl.page.auth.GithubTest
Running com.rexsl.core.PageAnalyzerTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.517 sec - in com.rexsl.core.PageAnalyzerTest

Results :

Failed tests:
  BasePageTest.convertsToXml:67
Expected: (an XML document with XPath /page/@date and an XML document with XPath /page/@ip and an XML document with XPath /page/@ssl and an XML document with XPath /page[number(@sla) > 0] and an XML document with XPath /page/millis and an XML document with XPath /page/single/x and an XML document with XPath /page/title[. = 'hello, world!'] and an XML document with XPath /page/links/link[@rel = 'home'] and an XML document with XPath /page/links/link[@rel = 'self'] and an XML document with XPath /page/links/link[@rel = 'test'])
     but: an XML document with XPath /page[number(@sla) > 0] was <<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<page date="2014-09-10T23:41:28.841+03:00" ip="105.161.21.119" sla="-1.000" ssl="false">
    <single>
        <x/>
    </single>
    <title>hello, world!</title>
    <links>
        <link href="http://localhost:99/foo" rel="test" type="text/xml"/>
        <link href="http://localhost:99/local/foo" rel="self" type="text/xml"/>
        <link href="http://localhost:99/" rel="home" type="text/xml"/>
    </links>
    <millis>1376</millis>
</page>
>

Tests run: 109, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by simonjenga** [comment]
@yegor256 From an older version of this project, it seems that Line 73 ```"/page[number(@sla) > 0]",``` makes the test to fail. What exactly does it do? Should it be deleted as a fix?

Please provide a go ahead on this so as we can close this issue ASAP :)

**Comment by yegor256** [comment]
the development of this framework is stopped. its successor is here: [takes.org](http://www.takes.org). I'm closing this issue since it won't get any attention any more. thanks all.
